apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: alphacar
type: Opaque
stringData:
  username: admin
  password: "123"
  host: "192.168.0.201"
  port: "27017"
  database: alphacar
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-aichat-secret
  namespace: alphacar
type: Opaque
stringData:
  username: proj
  password: "1234"
  host: "192.168.0.201"
  port: "27017"
  database: alphacar
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: alphacar
type: Opaque
stringData:
  password: "k8spass#"
  host: "192.168.0.175"
  port: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: alphacar
type: Opaque
stringData:
  username: team1
  password: "Gkrtod1@"
  host: "211.46.52.151"
  port: "15432"
  database: team1
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: alphacar
type: Opaque
stringData:
  secret: "your-jwt-secret-key-change-this-in-production"



